module.exports = {
	plugins: [
		{
			name: 'preset-default',
			params: {
				overrides: {
					removeViewBox: false,
					removeRasterImages: false,
					transformsWithOnePath: false,
				},
			},
		},
		'cleanupEnableBackground',
		'cleanupAttrs',
		'removeDoctype',
		'removeXMLProcInst',
		'removeComments',
		'removeMetadata',
		'removeTitle',
		'removeDesc',
		'removeUselessDefs',
		'removeEditorsNSData',
		'removeEmptyAttrs',
		'removeHiddenElems',
		'removeEmptyText',
		'removeEmptyContainers',
		'convertStyleToAttrs',
		'convertColors',
		'convertPathData',
		'convertTransform',
		'removeUnknownsAndDefaults',
		'removeNonInheritableGroupAttrs',
		'removeUselessStrokeAndFill',
		'removeUnusedNS',
		'cleanupNumericValues',
		'moveElemsAttrsToGroup',
		'moveGroupAttrsToElems',
		'collapseGroups',
		'mergePaths',
		'convertShapeToPath',
		'sortAttrs',
		'removeDimensions',
		{
			name: 'removeAttrs',
			params: {
				attrs: '(stroke|fill)',
			},
		},
	],
}
